kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - mesanine/init
  - linuxkit/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
  - linuxkit/containerd:18eaf72f3f4f9a9f29ca1951f66df701f873060b
  - linuxkit/ca-certificates:eabc5a6e59f05aa91529d80e9a595b85b046f935
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:2cf2f9d5b4d314ba1bfc22b2fe931924af666d8c"
    net: host
    pid: host
    ipc: host
    capabilities:
     - CAP_SYS_ADMIN
services:
  - name: rngd
    image: "linuxkit/rngd:3dad6dd43270fa632ac031e99d1947f20b22eec9"
    capabilities:
     - CAP_SYS_ADMIN
    oomScoreAdj: -800
  - name: dhcpcd
    image: "linuxkit/dhcpcd:48e249ebef6a521eed886b3bce032db69fbb4afa"
    binds:
     - /var:/var
     - /tmp:/etc
    capabilities:
     - CAP_NET_ADMIN
     - CAP_NET_BIND_SERVICE
     - CAP_NET_RAW
    net: host
    oomScoreAdj: -800
  - name: ntpd
    image: "linuxkit/openntpd:a570316d7fc49ca1daa29bd945499f4963d227af"
    capabilities:
      - CAP_SYS_TIME
      - CAP_SYS_NICE
      - CAP_SYS_CHROOT
      - CAP_SETUID
      - CAP_SETGID
    net: host
  - name: sshd
    image: mesanine/sshd
    capabilities:
      - all
    net: host
    pid: host
    binds:
     - /root/.ssh:/root/.ssh
     - /etc/resolv.conf:/etc/resolv.conf
  - name: nginx
    image: "nginx:alpine"
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    net: host
  - name: mesos
    image: quay.io/vektorcloud/mesos:combined-build
    command: ["/entrypoint.sh", "mesos-local"]
    env:
      - "DISCOVER_IP=true"
      - "MESOS_ZK=zk://localhost:2181/mesos"
      - "MESOS_MASTER=zk://localhost:2181/mesos" 
      - "MESOS_QUORUM=1" 
      - "MESOS_WORK_DIR=/var/run/mesos" 
      - "MESOS_LOG_DIR=/var/run/mesos/log" 
      - "MESOS_CONTAINERIZERS=mesos" 
      - "MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins" 
      - "MESOS_LAUNCHER=linux" 
      - "MESOS_LOGGING_LEVEL=WARNING" 
      - "MESOS_SYSTEMD_ENABLE_SUPPORT=false" 
      - "MESOS_ISOLATION=cgroups/cpu,cgroups/mem,cgroups/pids,namespaces/pid,filesystem/shared,filesystem/linux,docker/runtime,volume/sandbox_path" 
      - "MESOS_IMAGE_PROVIDERS=DOCKER,APPC"
    capabilities:
      - all
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
files:
  - path: root/.ssh/authorized_keys
    contents: '# YOUR PUBLIC RSA KEY #'
outputs:
  - format: kernel+initrd
