kernel: 
  image: "linuxkit/kernel:4.9.x" 
  cmdline: "console=ttyS0 console=tty0 page_poison=1" 
init:
  - mesanine/init
  - mesanine/runc
  - mesanine/gaffer

onboot:
  - name: sysctl
    image: "mesanine/sysctl"
  - name: binfmt
    image: "mesanine/binfmt"
  - name: dhcpcd
    image: "mesanine/dhcpcd"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: "mesanine/metadata"
services:
  - name: getty
    image: "mesanine/getty"
    env:
     - INSECURE=true
#  - name: rngd TODO: not needed in qemu
#    image: "linuxkit/rngd:b50b22dd574c5377708977af769f053009fff6d5"
  - name: sshd
    image: "mesanine/sshd"
    binds:
      - /var/config/ssh:/root/.ssh
      - /etc/resolv.conf:/etc/resolv.conf
      - /:/hostroot
  - name: master
    image: mesanine/mesos
    command: ["/entrypoint.sh", "mesos-master"]
    capabilities:
      - CAP_NET_BIND_SERVICE
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
  - name: agent
    image: mesanine/mesos
    command: ["/entrypoint.sh", "mesos-agent"]
    capabilities:
      - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
  - name: zookeeper
    image: mesanine/zookeeper
    command: ["/entrypoint.sh", "zkServer.sh", "start-foreground"]
    capabilities:
      - CAP_NET_BIND_SERVICE
    net: host
    pid: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
