kernel: 
  image: "linuxkit/kernel:4.9.40-91714b66fb6f39045bb5c79ecacb23eab1aa4bc3-dirty" 
init:
  - mesanine/init
  - mesanine/runc
  - mesanine/gaffer

onboot:
  - name: sysctl
    image: "mesanine/sysctl"
  - name: binfmt
    image: "mesanine/binfmt"
  - name: dhcpcd
    image: "mesanine/dhcpcd"
  - name: ignition
    image: "mesanine/ignition"
services:
  - name: sshd
    image: "mesanine/sshd"
  - name: etcd
    image: "mesanine/etcd"
  - name: zetcd
    image: "mesanine/zetcd"
  - name: mesos-master
    image: "mesanine/mesos-master"
  - name: mesos-agent
    image: "mesanine/mesos-agent"
