kernel: 
  image: "linuxkit/kernel:4.9.x" 
  cmdline: "console=ttyS0 console=tty0 page_poison=1" 
init:
  - mesanine/init
  - mesanine/runc
  - mesanine/gaffer
  - mesanine/metadata

onboot:
  - name: sysctl
    image: "mesanine/sysctl"
  - name: binfmt
    image: "mesanine/binfmt"
  - name: dhcpcd
    image: "mesanine/dhcpcd"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: "mesanine/getty"
    env:
     - INSECURE=true
#  - name: rngd TODO: not needed in qemu
#    image: "linuxkit/rngd:b50b22dd574c5377708977af769f053009fff6d5"
  - name: mesos
    image: mesanine/mesos
    command: ["/entrypoint.sh", "mesos-local"]
    env:
      - "DISCOVER_IP=true"
      - "MESOS_ZK=zk://localhost:2181/mesos"
      - "MESOS_MASTER=zk://localhost:2181/mesos" 
      - "MESOS_QUORUM=1" 
      - "MESOS_WORK_DIR=/var/run/mesos" 
      - "MESOS_LOG_DIR=/var/run/mesos/log" 
      - "MESOS_CONTAINERIZERS=mesos" 
      - "MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins" 
      - "MESOS_LAUNCHER=linux" 
      - "MESOS_LOGGING_LEVEL=WARNING" 
      - "MESOS_SYSTEMD_ENABLE_SUPPORT=false" 
      - "MESOS_ISOLATION=cgroups/cpu,cgroups/mem,cgroups/pids,namespaces/pid,filesystem/shared,filesystem/linux,docker/runtime,volume/sandbox_path" 
      - "MESOS_IMAGE_PROVIDERS=DOCKER,APPC"
    capabilities:
      - all
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
