#!/bin/sh
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#exec gaffer --debug --device=/dev/console init --single=true /mnt
exec /bin/gaffer --device=/dev/console --config="" init --stage=PRE_INIT
