FROM docker:17.06.0-ce-dind

LABEL org.mobyproject.config='{"pid": "host", "binds": ["/etc/resolv.conf:/etc/resolv.conf", "/var/lib/docker:/var/lib/docker", "/lib/modules:/lib/modules", "/var/run:/var/run"], "mounts": [{"type": "cgroup", "options": ["rw", "nosuid", "noexec", "nodev", "relatime"]}], "capabilities": ["all"]}'
