# Page settings
baseurl = "localhost:1313"
title = "Mesanine OS"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/mesanine.css"]

  # Meta
  author = "mesanine linux"
  description = "Linux distribution for running Apache Mesos"
  email = "info@mesanine.co"
  # Navigation
  [params.navigation]
    brand = "mesanine"
    home = "Home"
    work = "About"
    services = "Products"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "The first Linux distribution for Apache Mesos"
    subtitle = "Effortlessly deploy, run, and scale, containers with the industry's most proven platform."
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Getting Started"
    description = "Download the latest release"
    url = "#"
    button = "download"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Learn"
    description = "Read the documentation"
    url = "#"
    button = "learn"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Scale"
    description = "Scale further with Mesanine"
    url = "#"
    button = "profit"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false

  # Work section
  [params.work]
    enable = true
    title = "About"
    description = "Mesanine Linux is designed to ease the pains and complexities of running containers at scale with the most powerful platform in the industry."
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Minimal"
      subtitle = "Minimal at heart"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Stateless"
      subtitle = 'The end of "configuration drift"'

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Container-oriented"
      subtitle = "Container-oriented at heart"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Proven"
      subtitle = "The most proven containerization platform"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Secure"
        subtitle = "Minimal attack surface, grsecurity and musl-libc"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Flexible"
      subtitle = "Pick and choose the compontents you need"

  # Testimonials section
  [params.testimonials]
    enable = false

  # Services section
  [params.services]
    enable = true
    title = "Products"
    description = "Mesanine Linux offers enterprise features to sustain itself"

    [[params.services.item]]
        title = "mesos.co"
      description = "mesos.co provides a centralized configuration and coordination for enterprise deployments"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "consulting services"
      description = "mesanine offers professional consulting services"
      icon = "icon-layers2"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Mesanine Linux is still in alpha, drop us your name and e-mail and we'll be in touch."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-envelope", "info@mesanine.co"],
        ["icon-globe", '<a href="http://mesanine.co/" target="_blank">mesanine.co</a>']
      ]

    name = "Name"
    email = "Email"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Mesanine Linux. All Rights Reserved. <br>Crafted with ♥ by <a href="http://vektor.nyc" target="_blank">vektorlab</a>'
