#!/bin/sh

GAFFER="/usr/bin/gaffer"
LOG_DEVICE="/dev/ttyS0"

# Debug mode is toggleable with kernel parameters
if [[ "$(grep 'gaffer=debug' /proc/cmdline)" ]] ; then {
  GAFFER="$GAFFER --debug --device=$LOG_DEVICE"
} else {
  GAFFER="$GAFFER --device=$LOG_DEVICE"
}
fi

# Run each onboot container to completion
$GAFFER --hard=true init --once /containers/onboot

# Make Mesos run dir
# TODO: move elsewhere
mkdir -p /var/run/mesos

# Wait until we've aquired agent metadata
# before going forward. # TODO: Need a better
# way to wait until all underlying subsystems
# are initialized and we can go forward with 
# the boot process.
#$GAFFER wait /var/mesanine/mesos-agent

# Run the Gaffer init process
$GAFFER --hard=true init /containers/services &

# Launch the Gaffer web UI
#$GAFFER server &
