FROM quay.io/vektorcloud/marathon

ENV LIBPROCESS_IP=127.0.0.1
ENV MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos-1.3.0.so

LABEL org.mobyproject.config='{"pid": "host", "capabilities": ["CAP_NET_BIND_SERVICE"]}'
