FROM quay.io/vektorcloud/go:1.8 AS source

RUN apk add --no-cache bash musl-dev util-linux-dev

COPY ignition/ /go/src/github.com/coreos/ignition/

RUN cd /go/src/github.com/coreos/ignition \
  && sed -i -e 's/VERSION=.*/VERSION=mesanine/' ./build \
  && PLATFORM=linuxkit ./build \
  && mv -v bin/amd64/ignition /

FROM scratch 

COPY --from=source /ignition /
