#!/bin/sh
set -x

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# mount proc filesystem
mount -n -t proc proc /proc -o nodev,nosuid,noexec,relatime

# mount sysfs
mount -n -t sysfs -o nodev,noexec,nosuid sysfs /sys

# load devices
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# We need link-local addresses
# for collecting userdata on
# most oem e.g. EC2
ip link set eth0 up

function recovery() {
  echo "Warning! Init failed, you have been dropped to a recovery shell!"
  exec /bin/sh
}

ln -sv /usr/bin/sgdisk /sbin/sgdisk

/usr/bin/ignition --stage disks --oem $(cat /oem)

[[ $? -eq 0 ]] || recovery

# Call init.go
exec /switch_root

# Second --stage files ignition commands happens after init
